---
all:
  hosts:
    gonnux-server:
      ansible_port: 22
      ansible_host: 192.168.10.254
      ansible_python_interpreter: /usr/bin/python3
      #ansible_user: vagrant
      #ansible_ssh_private_key_file: .vagrant/machines/default/libvirt/private_key
