---
all:
  hosts:
    gonapps-server:
      ansible_port: 22
      ansible_host: 192.168.121.254
      ansible_user: vagrant
      #ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_ssh_private_key_file: .vagrant/machines/default/libvirt/private_key
      ansible_python_interpreter: /usr/bin/python
