---
- name: gonapps.com-ansible
  hosts: all
  tasks:
########

    - name: set-hostname
      tags: set-hostname
      become: true
      hostname:
        name: gonapps-vm

    - name: uninstall-dnf-packages
      tags: uninstall-dnf-packages
      become: true
      dnf:
        name: '{{ item }}'
        state: absent
      loop:
        - docker
        - firewalld
        - podman
        - podman-manpages

    - name: download-docker-ce
      tags: download-docker-ce
      become: true
      uri:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        status_code:
          - 200
          - 304

    - name: dnf-makecache
      tags: dnf-makecache
      become: true
      dnf:
        update_cache: true

    - name: install-dnf-packages
      tags: install-dnf-packages
      become: true
      dnf:
        name: '{{ item }}'
        state: latest
      loop:
        - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.2-3.3.el7.x86_64.rpm
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - cockpit
        - docker-ce
        - epel-release
        - fail2ban
        - gcc
        - gcc-c++
        - git
        - go
        - iptables-utils
        - iptables-services
        - libselinux
        - libselinux-utils
        - npm
        - policycoreutils
        - policycoreutils-python-utils
        - python3
        - python3-devel
        - python3-libselinux
        - python3-pip
        - python3-policycoreutils

    - name: disable-selinux
      tags: disable-selinux
      become: true
      selinux:
        policy: targeted
        state: permissive

    - name: install-pip3-packages
      tags: install-pip3-packages
      become: true
      pip:
        executable: pip3
        name: '{{ item }}'
        state: latest
      loop:
        - docker
        - docker-compose

########

    - name: mkdir-opt-hugo
      tags: mkdir-opt-hugo
      become: true
      file:
        path: /opt/hugo
        state: directory
        mode: '777'

    - name: chmod-srv
      tags: chmod-srv
      become: true
      file:
        path: /srv
        state: directory
        mode: '777'

    - name: mkdir-srv-vol-data
      tags: mkdir-srv-vol-data
      file:
        path: /srv/vol/data
        state: directory

    - name: sudo-copy-files
      tags: sudo-copy-files
      become: true
      copy:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['./conf/etc/sysconfig/iptables', '/etc/sysconfig/iptables']
        - ['./conf/etc/fail2ban/jail.local', '/etc/fail2ban/jail.local']

    - name: copy-files
      tags: copy-files
      copy:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['./conf/srv/docker-compose.yml', '/srv/docker-compose.yml']
        - ['./vol', '/srv']

    - name: sync-git-repos
      tags: sync-git-repos
      git:
        repo: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['https://github.com/gohugoio/hugo', '/opt/hugo']
        - ['https://github.com/gonapps-org/gonapps.com-home', '/srv/vol/data/gonapps.com-home']
        - ['https://github.com/gonapps-org/calc', '/srv/vol/data/calc']
        - ['https://github.com/gonapps-org/libgenc', '/srv/vol/data/libgenc']
        - ['https://github.com/stellar-fighter/stellar-fighter', '/srv/vol/data/stellar-fighter']
        - ['https://github.com/vinbero/vinbero', '/srv/vol/data/vinbero']

    - name: install-hugo
      tags: install-hugo
      become: true
      command: go install --tags extended
      environment:
        GOPATH: /usr/local/go
      args:
        chdir: /opt/hugo
        creates: /usr/local/go/bin/hugo

    - name: run-npm-install
      tags: run-npm-install
      command: npm install
      args:
        chdir: '{{ item }}'
      loop:
        - /srv/vol/data/calc
        - /srv/vol/data/stellar-fighter

    - name: run-npm-run-build
      tags: run-npm-run-build
      command: npm run build
      args:
        chdir: '{{ item }}'
      loop:
        - /srv/vol/data/calc
        - /srv/vol/data/stellar-fighter

    - name: local-copy-files
      tags: local-copy-files
      copy:
        remote_src: yes
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['/srv/vol/data/calc/dist/', '/srv/vol/data/gonapps.com-home/content/apps/calc']
        - ['/srv/vol/data/stellar-fighter/dist/', '/srv/vol/data/gonapps.com-home/content/apps/stellar-fighter']

    - name: run-hugo
      tags: run-hugo
      command: /usr/local/go/bin/hugo
      args:
        chdir: /srv/vol/data/gonapps.com-home
        creates:
          - /srv/vol/data/gonapps.com-home/public/index.html

########

    - name: openssl-ca-key
      tags: make-openssl-cert
      openssl_privatekey:
        path: /srv/vol/data/server-ca.pem
        size: 4096

    - name: openssl-ca-csr
      tags: make-openssl-cert
      openssl_csr:
        path: /srv/vol/data/server-ca.csr
        privatekey_path: /srv/vol/data/server-ca.pem

    - name: openssl-ca-cert
      tags: make-openssl-cert
      openssl_certificate:
        path: /srv/vol/data/server-ca.crt
        privatekey_path: /srv/vol/data/server-ca.pem
        csr_path: /srv/vol/data/server-ca.csr
        provider: selfsigned

    - name: openssl-key
      tags: make-openssl-cert
      openssl_privatekey:
        path: /srv/vol/data/server.pem
        size: 4096

    - name: openssl-csr
      tags: make-openssl-cert
      openssl_csr:
        path: /srv/vol/data/server.csr
        privatekey_path: /srv/vol/data/server.pem

    - name: openssl-cert
      tags: make-openssl-cert
      openssl_certificate:
        path: /srv/vol/data/server.crt
        privatekey_path: /srv/vol/data/server.pem
        csr_path: /srv/vol/data/server.csr
        ownca_path: /srv/vol/data/server-ca.crt
        ownca_privatekey_path: /srv/vol/data/server-ca.pem
        provider: ownca

########

    - name: add-group
      tags: add-group
      become: true
      group:
        name: 'docker'
        state: present

    - name: add-group-user
      tags: add-group-user
      become: true
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes

    - name: reset-ssh
      tags: reset-ssh
      meta: reset_connection

########

    - name: stop-service
      tags: service
      become: true
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: false
      loop:
        - firewalld

    - name: start-service
      tags: start-service
      become: true
      systemd:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - iptables
        - fail2ban
        - cockpit.socket

    - name: restart-service
      tags: service
      become: true
      systemd:
        name: '{{ item }}'
        state: restarted
        enabled: true
      loop:
        - docker

    - name: docker-compose
      tags: docker-compose
      docker_compose:
        project_src: /srv
