---
- name: gonnux.com-ansible
  hosts: all
  gather_facts: yes
  tasks:
########
    - name: print-facts
      tags: print-facts
      debug:
        var: ansible_facts

    - name: assert-distribution
      assert:
        that:
          - '"{{ ansible_distribution }}" == "Ubuntu"'
          - '"{{ ansible_distribution_release }}" == "focal"'

    - name: set-hostname
      tags: set-hostname
      become: true
      hostname:
        name: '{{ inventory_hostname }}'

    - name: update-upgrade-apt
      become: true
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: install-apt-packages
      tags: install-apt-packages
      become: true
      apt:
        name: '{{ item }}'
        state: latest
      loop:
        - iptables-persistent
        - fail2ban
        - cockpit

########

    - name: make-dirs
      tags: make-dirs
      become: true
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - '/srv/vol/data'

    - name: sudo-copy-files
      tags: sudo-copy-files
      become: true
      copy:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['./conf/etc/', '/etc']
        - ['./conf/srv/', '/srv']
        - ['./vol', '/srv']

########

    - name: start-service
      tags: start-service
      become: true
      systemd:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - iptables
        - cockpit.socket
        - fail2ban

    - name: reboot
      tags: reboot
      become: true
      reboot:
