---
- name: gonapps.com-ansible
  hosts: all
  tasks:
########

    - name: set-hostname
      tags: set-hostname
      become: true
      hostname:
        name: gonapps-vm

    - name: uninstall-dnf-packages
      tags: uninstall-dnf-packages
      become: true
      dnf:
        name: '{{ item }}'
        state: absent
      loop:
        - docker
        - firewalld
        - podman
        - podman-manpages

    - name: download-docker-ce
      tags: download-docker-ce
      become: true
      uri:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        status_code:
          - 200
          - 304

    - name: dnf-makecache
      tags: dnf-makecache
      become: true
      dnf:
        update_cache: true

    - name: install-dnf-packages
      tags: install-dnf-packages
      become: true
      dnf:
        name: '{{ item }}'
        state: latest
      loop:
        - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.2-3.3.el7.x86_64.rpm
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - cockpit
        - docker-ce
        - epel-release
        - fail2ban
        - gcc
        - gcc-c++
        - git
        - go
        - iptables-utils
        - iptables-services
        - libselinux
        - libselinux-utils
        - npm
        - policycoreutils
        - policycoreutils-python-utils
        - python3
        - python3-devel
        - python3-libselinux
        - python3-pip
        - python3-policycoreutils

    - name: disable-selinux
      tags: disable-selinux
      become: true
      selinux:
        policy: targeted
        state: permissive

    - name: install-pip3-packages
      tags: install-pip3-packages
      become: true
      pip:
        executable: pip3
        name: '{{ item }}'
        state: latest
      loop:
        - docker
        - docker-compose

########

    - name: copy-files
      tags: copy-files
      become: true
      copy:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['./conf/etc/sysconfig/iptables', '/etc/sysconfig/iptables']
        - ['./conf/srv/docker-compose.yml', '/srv/docker-compose.yml']
        - ['./conf/etc/fail2ban/jail.local', '/etc/fail2ban/jail.local']
        - ['./vol', '/srv/']

    - name: mkdir-srv-vol-data
      tags: mkdir-srv-vol-data
      become: true
      file:
        path: /srv/vol/data
        state: directory

    - name: sync-git-repos
      tags: sync-git-repos
      become: true
      git:
        repo: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['https://github.com/gonapps-org/gonapps.com-home', '/srv/vol/data/gonapps.com-home']
        - ['https://github.com/gohugoio/hugo', '/opt/hugo']

    - name: install-hugo
      tags: install-hugo
      become: true
      command: go install --tags extended
      environment:
        GOPATH: /usr/local/go
      args:
        chdir: /opt/hugo
        creates: /usr/local/go/bin/hugo

    - name: run-hugo
      tags: run-hugo
      become: true
      command: /usr/local/go/bin/hugo
      args:
        chdir: /srv/vol/data/gonapps.com-home
        creates:
          - /srv/vol/data/gonapps.com-home/public/index.html

########

    - name: openssl-ca-key
      tags: make-openssl-cert
      become: true
      openssl_privatekey:
        path: /srv/vol/data/server-ca.pem
        size: 4096

    - name: openssl-ca-csr
      tags: make-openssl-cert
      become: true
      openssl_csr:
        path: /srv/vol/data/server-ca.csr
        privatekey_path: /srv/vol/data/server-ca.pem

    - name: openssl-ca-cert
      tags: make-openssl-cert
      become: true
      openssl_certificate:
        path: /srv/vol/data/server-ca.crt
        privatekey_path: /srv/vol/data/server-ca.pem
        csr_path: /srv/vol/data/server-ca.csr
        provider: selfsigned

    - name: openssl-key
      tags: make-openssl-cert
      become: true
      openssl_privatekey:
        path: /srv/vol/data/server.pem
        size: 4096

    - name: openssl-csr
      tags: make-openssl-cert
      become: true
      openssl_csr:
        path: /srv/vol/data/server.csr
        privatekey_path: /srv/vol/data/server.pem

    - name: openssl-cert
      tags: make-openssl-cert
      become: true
      openssl_certificate:
        path: /srv/vol/data/server.crt
        privatekey_path: /srv/vol/data/server.pem
        csr_path: /srv/vol/data/server.csr
        ownca_path: /srv/vol/data/server-ca.crt
        ownca_privatekey_path: /srv/vol/data/server-ca.pem
        provider: ownca

########

    - name: add-group
      tags: add-group
      become: true
      group:
        name: 'docker'
        state: present

    - name: add-group-user
      tags: add-group-user
      become: true
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes

    - name: reset-ssh
      tags: reset-ssh
      meta: reset_connection

########

    - name: firewalld-service
      tags: service
      become: true
      systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: iptables-service
      tags: service
      become: true
      systemd:
        name: iptables
        state: started
        enabled: true

    - name: fail2ban-service
      tags: service
      become: true
      systemd:
        name: fail2ban
        state: started
        enabled: true

    - name: cockpit-service
      tags: service
      become: true
      systemd:
        name: cockpit.socket
        state: started
        enabled: true

    - name: docker-service
      tags: service
      become: true
      systemd:
        name: docker
        state: restarted
        enabled: true

    - name: docker-compose
      tags: docker-compose
      docker_compose:
        project_src: /srv
