---
- name: gonnux.com-ansible
  hosts: all
  gather_facts: yes
  tasks:
########
    - name: print-facts
      tags: print-facts
      debug:
        var: ansible_facts

    - name: assert-distribution
      assert:
        that:
          - '"{{ ansible_distribution }}" == "Ubuntu"'
          - '"{{ ansible_distribution_release }}" == "focal"'

    - name: set-hostname
      tags: set-hostname
      become: true
      hostname:
        name: gonnux.com-vm

    - name: update-upgrade-apt
      become: true
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: install-apt-packages
      tags: install-apt-packages
      become: true
      apt:
        name: '{{ item }}'
        state: latest
      loop:
        - cockpit
        - docker
        - docker-compose
        - fail2ban
        - gcc
        - g++
        - git
        - iptables-persistent
        - policycoreutils
        - selinux-basics
        - selinux-utils

          #    - name: disable-selinux
          #      tags: disable-selinux
          #      become: true
          #      ansible.posix.selinux:
          #        policy: targeted
          #        state: permissive
    - name: install-minikube
      tags: install-minikube
      become: true
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/bin/minikube
        mode: 0755

    - name: get-kubectl-stable-release
      tags: get-kubectl-stable-release
      uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubectl_stable_release

    - name: install-kubectl
      tags: install-kubectl
      become: true
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_stable_release.content }}/bin/linux/amd64/kubectl"
        dest: /usr/bin/kubectl
        mode: 0755

    - name: start-minikube
      tags: start-minikube
      command: minikube start

########

    - name: make-dirs
      tags: make-dirs
      become: true
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - '/srv/vol/data'

    - name: sudo-copy-files
      tags: sudo-copy-files
      become: true
      copy:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
      loop:
        - ['./conf/etc/iptables', '/etc/iptables']
        - ['./conf/etc/fail2ban/jail.local', '/etc/fail2ban/jail.local']
        - ['./conf/srv/', '/srv']
        - ['./vol', '/srv']

########

    - name: openssl-ca-key
      tags: make-openssl-cert
      become: true
      openssl_privatekey:
        path: /srv/vol/data/server-ca.pem
        size: 4096

    - name: openssl-ca-csr
      tags: make-openssl-cert
      become: true
      openssl_csr:
        path: /srv/vol/data/server-ca.csr
        privatekey_path: /srv/vol/data/server-ca.pem

    - name: openssl-ca-cert
      tags: make-openssl-cert
      become: true
      openssl_certificate:
        path: /srv/vol/data/server-ca.crt
        privatekey_path: /srv/vol/data/server-ca.pem
        csr_path: /srv/vol/data/server-ca.csr
        provider: selfsigned

    - name: openssl-key
      tags: make-openssl-cert
      become: true
      openssl_privatekey:
        path: /srv/vol/data/server.pem
        size: 4096

    - name: openssl-csr
      tags: make-openssl-cert
      become: true
      openssl_csr:
        path: /srv/vol/data/server.csr
        privatekey_path: /srv/vol/data/server.pem

    - name: openssl-cert
      tags: make-openssl-cert
      become: true
      openssl_certificate:
        path: /srv/vol/data/server.crt
        privatekey_path: /srv/vol/data/server.pem
        csr_path: /srv/vol/data/server.csr
        ownca_path: /srv/vol/data/server-ca.crt
        ownca_privatekey_path: /srv/vol/data/server-ca.pem
        provider: ownca

########

    - name: add-group
      tags: add-group
      become: true
      group:
        name: 'docker'
        state: present

    - name: add-group-user
      tags: add-group-user
      become: true
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes

    - name: reset-ssh
      tags: reset-ssh
      meta: reset_connection

########

    - name: start-service
      tags: start-service
      become: true
      systemd:
        name: '{{ item }}'
        state: started
        enabled: true
      loop:
        - iptables
        - fail2ban
        - cockpit.socket
        - docker

    - name: docker-compose
      tags: docker-compose
      community.docker.docker_compose:
        project_src: /srv
